### ISSUE TITLE
typing "firebase use <project_id>" gets syntax error

### ISSUE THREAD

**Issue by flagz404** [google-home/smarthome-washer#42]

**Comment by shannonhwu-google** [comment]
Hi flagz404,

Thanks for your question.

<project_id> is a placeholder for your actual project ID, so in this case instead of typing "firebase use <project_id>", you want to replace the placeholder as such: "firebase use my-test-project-0000". 

If you don't know the project ID for your smart home Action, then you can find it in the Actions console under "Project settings".
